name: Run Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          npm install

      - name: Install additional dependencies for headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libx11-xcb1

      - name: Run tests
        run: |
          node login_test.js