{
  "name": "hemie-tests",
  "version": "1.0.0",
  "description": "Selenium tests for Hemie",
  "type": "module",
  "scripts": {
    "test": "mocha login_test.js --timeout 60000"
  },
  "dependencies": {
    "selenium-webdriver": "^4.21.0",
    "chromedriver": "^124.0.0"
  },
  "devDependencies": {
    "mocha": "^10.2.0",
    "chai": "^4.3.7"
  }
}